name: automerge
on:
  schedule:
    - cron: "*/30 * * * *"
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      # checks out out repo to $GITHUB_WORKSPACE
      # note: this has to be a full clone to avoid "fatal: refusing to merge unrelated histories"
      - uses: actions/checkout@v1
        uses: ./automerge
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          MERGE_LABEL: "automerge"
