name: delete-merged-branch

on:
  pull_request:
    types: [closed]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: opensesame/Actions/delete-merged-branch@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
